### PR TITLE
Port automation suite from the mkumatag personal repo without history

### PR DESCRIPTION
**Pull request by causten**
All these files came from https://github.com/mkumatag/openbmc-automation
The decision to remove the commit history was because most of the 122
commits did not follow commit comment AND content best practices.
The ability to remove the commit history was possible because all
contributors where from the same company (IBM) making the coordination /
notification/acceptence easy.  See all the gory details about the
first try to commit with history here...
https://github.com/openbmc/openbmc-test-automation/pull/1

This suite of tests will run against an OpenBMC based server.  It will
run good/bad path testing against the REST interface.  There are tests
that will also run ipmitool on the victim BMC too.

If you want to support a new system in to the suite you should only
have to edit two files...
    data/<system>.py
    tox.ini

The README.md contains details on how to setup for the first time along
with how to execute the test suite

---
This change is [Reviewable](https://reviewable.io/reviews/openbmc/openbmc-test-automation/2)

### CODE REVIEW

**Comment by anoo1** [comment]
hi @causten , reviewing with Patrick, please remove the binary tool ipmitool from this PR. All binaries should be built and not be part of the checked in code.

**Comment by mdmillerii** [comment]
I pointed out via chat the commit and title said _with history_ instead of _without history_.
I see the pull request subject was fixed, unfortunately the subject title in commit subject was not fixed.

(I haven't yet done further review).

**Comment by mkumatag** [comment]
@anoo1 : The reason behind ipmitool binary kept in the code because we don't have that tool present in the openbmc. IMO building ipmitool is not a good idea, probably we can push that somewhere and copy it to part of tox script as prereq or include that into openbmc code itself so that tests can use without copying it.

**Comment by williamspatrick** [comment]
Merged manually to master.

**Pull request closed without merging**
