### PR TITLE
test_openbmc_setup.robot: fix format

### PR DESCRIPTION
**Pull request by chosteven**
test_openbmc_setup.robot: fix format

neat the code

```
Tested:
------------------------------------------------------------------------------ 
Test Openbmc Setup.Test Openbmc Setup :: Test suite to verify if t... | PASS | 
3 tests, 3 passed, 0 failed
==============================================================================
Test Openbmc Setup                                                    | PASS |
3 tests, 3 passed, 0 failed
==============================================================================
Output:  /tmp/root/20130/obmc-robot/output.xml
Log:     /tmp/root/20130/obmc-robot/log.html
Report:  /tmp/root/20130/obmc-robot/report.html
```

### CODE REVIEW

**Comment by gkeishin** [comment]
@chosteven  Please refer this https://github.com/openbmc/docs/blob/master/CONTRIBUTING.md#submitting-changes-via-gerrit-server-to-openbmc


For OpenBMC we use gerrit to submit changes.

**Comment by chosteven** [comment]
Got it. Submitted CL on gerrit
https://gerrit.openbmc.org/c/openbmc/openbmc-test-automation/+/70487

**Comment by gkeishin** [comment]
@chosteven I don't see your name in the approved list for **Inventec**  

https://drive.google.com/drive/folders/19RJNsE9nnNV8pMnV-6Q63mbhDMXKTUo1

can you talk to Vic Ye to get your name added before I can merge the gerrit commit patch changes.. 

**CLA Manager:**
Vic Ye ye.vic@inventec.com

**Comment by gkeishin** [comment]
Closing this PR as mentioned earlier to push via gerrit

**Pull request closed without merging**
